### ISSUE TITLE
Crash while clicking 

### ISSUE THREAD

**Issue by knoxhack** [shadowfacts/InductionCharger#2]
I crashed when I tried to put a tesla powered item in it.
this is an item from my mod im working on btw.

Idk if this is my fault.

https://gist.github.com/knoxhack/9f3fe321b0b7fb6d383573b1f87118ec

**Comment by shadowfacts** [comment]
This shouldn't be possible. Try redownloading ShadowMC

**Comment by knoxhack** [comment]
dont mind this is just my code that sucks
