### ISSUE TITLE
"Infinite Induction Charger" glitch crash

### ISSUE THREAD

**Issue by Yandols** [shadowfacts/InductionCharger#4]
So I tried crafting one of these induction charger and placed it down.
It worked. The problem is, there is still an invisible infinite amount of it in the hotbar slot I just used to place it down, despite it being empty. When I click on the ground it places another one but this time it also says `<ERROR>` in Waila and I can place as many of these Induction Chargers in the world despite having an empty hand slot. When interacting with it either by right clicking or left clicking it (trying to break it) the game crashes.

Crashlog is as follows:
http://pastebin.com/cEXx4LXC

Version numbers:
Minecraft 1.10.2
Forge Build 2014
ShadowMC 1.10.2-3.4.4
Induction Charger 1.10.2.-1.1.0

**Comment by shadowfacts** [comment]
Fixed in [1.1.1](https://github.com/shadowfacts/InductionCharger/releases/tag/1.10.2-1.1.1). (Currently pending approval on CurseForge)
