### ISSUE TITLE
1.12-1.4.1 crashes dedicated server Forge 1.12 build 2400

### ISSUE THREAD

**Issue by kreezxil** [shadowfacts/InductionCharger#9]
Notes:
     on startup, no class defined

crash report:
https://gist.github.com/a1a7e9c0b20876bbe57e2d50954d0da9

fml server latest:
https://gist.github.com/81ac02f6e9dea125d86a6f30452c06b5

**Comment by shadowfacts** [comment]
Again, [Redstone Flux](https://minecraft.curseforge.com/projects/redstone-flux) is required. The same UU bug may or may not be present in IC.
